### ISSUE TITLE
3.4.6 task list.

### ISSUE THREAD

**Issue by ShikiSuen** [ShikiSuen/vChewing-CHS#416]
- [x] 工具提示视窗不要使用系统的文字颜色与背景颜色，不然的话很难做 dark mode awareness。
- [x] 除非開啟偵錯模式，否則會使用系統的提示聲、而非輸入法本身的貝斯撥弦聲。
- [x] 更新鐵恨注拼引擎，徹底解決其動態注音鍵盤佈局處理當中的潛在的邏輯錯誤（雖然迄今為止沒有發作）。
- [x] 修复在藉由 Emoji 面板輸入 Emoji 之後崩礦的故障。
